services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm
    command: seed
    environment:
      - XTRABACKUP_PASSWORD=xtrabackup_secret
      - SYSTEM_PASSWORD=xtrabackup_secret
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - CLUSTER_NAME=nextcloud_cluster
    volumes:
      - db:/var/lib/mysql
    networks:
      - db_network
      - lb_loadbalancer
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none

  db:
    image: colinmollenhour/mariadb-galera-swarm
    command: node tasks.cloud_seed,tasks.cloud_db
    environment:
      - XTRABACKUP_PASSWORD=xtrabackup_secret
      - SYSTEM_PASSWORD=xtrabackup_secret
      - CLUSTER_NAME=nextcloud_cluster
      - GCOMM_MINIMUM=1
      - HEALTHY_WHILE_BOOTING=1
      - MYSQL_ROOT_PASSWORD=root
      - SKIP_UPGRADES=1
      
    volumes:
      - db:/var/lib/mysql
    networks:
      - db_network
      - lb_loadbalancer
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        preferences:
          - spread: node.hostname
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  nextcloud:
    image: registry.gitlab.com/tcoupin/nextcloud-slowfs:31
    restart: always
    # ports:
    #   - 80:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html-shared
    environment:
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=user
      - NEXTCLOUD_ADMIN_PASSWORD=pIBRAHIMAassw&*ordrghiudgh54
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.tsic2026.duckdns.org nextcloud
      - REDIS_HOST=redis       
      - REDIS_HOST_PORT=6379

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        preferences:
          - spread: node.labels.region
          - spread: node.hostname

      labels:
        # Enable Service discovery for Traefik
        - "traefik.enable=true"
        # Define the nextcloud router rule
        - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.tsic2026.duckdns.org`)"
        # Expose the nextcloud port number to Traefik
        - traefik.http.services.nextcloud.loadbalancer.server.port=80

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - db_network
      - nextonly_network
      - lb_loadbalancer

  nextcloud-exporter:
    image: "xperimental/nextcloud-exporter"
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - 9205:9205
    deploy: 
      replicas: 1
    cap_add:
      - MKNOD
    environment:
      - NEXTCLOUD_SERVER=http://nextcloud
      - NEXTCLOUD_AUTH_TOKEN=176e614fbe8e168631532aff2625ea40edd63bd1e5902c78cc03dd12e56d41d8
      - NEXTCLOUD_LISTEN_ADDRESS=:9205
      - NEXTCLOUD_TLS_SKIP_VERIFY=false

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    command: 
      --mysqld.address=db:3306 
      --mysqld.username=root 
    environment: 
      - MYSQLD_EXPORTER_PASSWORD=root
    ports:
      - 9104:9104
    networks:
      - lb_loadbalancer


  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    links:
      - nextcloud
    # ports:
    #   - 8082:80
    environment:
      - JWT_SECRET=secret
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        preferences:
          - spread: node.labels.region
          - spread: node.hostname

      labels:
        # Enable Service discovery for Traefik
        - "traefik.enable=true"
        # Define the onlyoffice router rule
        - "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.tsic2026.duckdns.org`)"
        # Expose the onlyoffice port number to Traefik
        - traefik.http.services.onlyoffice.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - nextonly_network
      - lb_loadbalancer
  
  redis:
    image: redis:alpine
    deploy:
      replicas: 1
    networks:
      - db_network

networks:
  lb_loadbalancer:
    external: true
  db_network:
    driver: overlay
  nextonly_network:
    driver: overlay

volumes:
  nextcloud:
    driver: glusterfs
  db:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'
    driver: glusterfs
  document_data:
    driver: glusterfs
  document_log:
    driver: glusterfs
