services:

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    deploy:
      mode: global

    networks:
      - monitoring

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

  nextcloud-exporter:
    image: "xperimental/nextcloud-exporter"
    security_opt:
      - no-new-privileges:true
    ports:
      - 9205:9205
    cap_add:
      - MKNOD
    environment:
      - NEXTCLOUD_SERVER=http://nextcloud:80
      - NEXTCLOUD_AUTH_TOKEN=a2bd0bce5d1f267a83764dbef0c80293890b5fd63549dee2086665e65a1ccdff
      - NEXTCLOUD_LISTEN_ADDRESS=:9205
      - NEXTCLOUD_TLS_SKIP_VERIFY=false

    networks:
      - monitoring

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    command: 
      --mysqld.address=db:3306 
      --mysqld.username=root 
    environment: 
      - MYSQLD_EXPORTER_PASSWORD=user
    ports:
      - 9104:9104
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    
  prometheus:
    image: prom/prometheus:main-distroless

    command:
      - '--config.file=/prometheus.yaml'

    configs:
      - source: prometheus_config
        target: '/prometheus.yaml'

    networks:
      - monitoring

    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - monitoring


configs:
  prometheus_config:
    file: 'prometheus.yaml'


networks:
  monitoring:


volumes:
  grafana_data:
  nextcloud_exporter_conf:
    driver: local
  